[book]
authors = ["keyword generics Members"]
language = "en"
multilingual = false
src = "."
title = "keyword generics initiative"

[output.html]
no-section-label=true
git-repository-url="https://github.com/rust-lang/keyword-generics"
edit-url-template="https://github.com/rust-lang/keyword-generics/edit/master/{path}"
site-url="/keyword-generics/"

[output.html.fold]
enable = true
level = 0
